# Acceptance (acc) stage - subscribes directly to the warehouse
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: acc
  namespace: hello-kargo
spec:
  subscriptions:
    warehouse: hello-kargo

  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: git@github.com:anasgrt/rancher-argocd-test.git
          checkout:
          - branch: main
            path: ./src
          - branch: stage/acc
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: copy
        config:
          inPath: ./src
          outPath: ./out
      - uses: git-commit
        config:
          path: ./out
          messageFromSteps: [0]
      - uses: git-push
        config:
          path: ./out

---
# Production (prd) stage - subscribes to acc stage
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prd
  namespace: hello-kargo
spec:
  subscriptions:
    upstreamStages:
    - name: acc

  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: git@github.com:anasgrt/rancher-argocd-test.git
          checkout:
          - branch: main
            path: ./src
          - branch: stage/prd
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: copy
        config:
          inPath: ./src
          outPath: ./out
      - uses: git-commit
        config:
          path: ./out
          messageFromSteps: [0]
      - uses: git-push
        config:
          path: ./out
