apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: hello-kargo
  namespace: hello-kargo
  annotations:
    # Kargo will retry automatically when secret becomes available
    kargo.akuity.io/description: "Monitors main branch for new commits"
    # Fleet: Apply after Project creates namespace
    fleet.cattle.io/apply-weight: "1"
    # Ignore Kargo's normalization of interval field (1m -> 1m0s)
    fleet.cattle.io/ignore-diff: "spec.interval"
spec:
  # Refresh interval - Kargo will retry if credentials fail
  # Using full duration format to match Kargo's normalization
  interval: 1m0s
  # Monitor the main branch of the Git repository
  subscriptions:
  - git:
      repoURL: git@github.com:anasgrt/rancher-argocd-test.git
      branch: main
      strictSemvers: false  # Accept all commits, not just semver tags
      discoveryLimit: 20
      commitSelectionStrategy: NewestFromBranch
